sudo: false
language: python
python:
- '3.4'
addons:
  apt:
    packages:
    - gnuplot
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texinfo
    - mercurial
install:
- pip install git+https://github.com/sphinx-doc/sphinx@stable
- pip install sphinx_bootstrap_theme
- pip list
script:
- GH_USER=LoyolaChicagoBooks GH_REPO=scala-tdd "./gh-pages.sh"
env:
  global:
    secure: oHpXI+ljOLmziZRXg2oQU6ON7QAf+3hpCklKPFuRBNH4O3RALd5Y1rIxazC1qqNVXWipXWkrTXX6I4MbZz6mwzbxNs0rOfZ28s8HttDnzWhZqZnxx6Y6O+1GSm+C+BhCDzadei4oz9mYM7xGx6PNHNR9ttd/vlsxD9s9zCrycQrtS7HFO7Jl0u6v2hsEoBRgWjcLPHqYfRwoeV2b79Vh4MYptx8BfkFbJzsf92+Wnqk/dwwV5dYdwNpOvt5eIpIcpnTpI2MUr8NZd9v7vfzVoiD6mvSVX0RA2jSVg6Hgt3YONui6GAbeGkL2bSxrL0fD0Gu+tnV5VoNoKY7UVQW2sPyRqL6fDhxtueq9QjRRnFlFIDkeXPsDY/SG24qelcWLGzWa+NeCr+9WNyKrpagSOdnl6ikDG2GDeTd1v51Q7MfQSE4DgSD49fkB3lTfdQXpTYIhnRWmEFSL0E2WlA5JEuhNpMhgh245aw23B7SHryVIdSUCktjXOfG+b/tczOMNY29xFaySLgPstvQaTcTwJxJ/9V8tPQ04DvAcQqHASLixk1wZ7huPBWRx5FH7mIk898FjDqjXNX/H1qkTlfmP48kex0OoMlFlByexS4RIBf3mpMvxYBnQkgYALGEaG0kTxJoubqTQ8wZzaQmpeEp3VQjycKRT/mttmGkfo43O+Sc=
